name: Deploy Tinyr to Heroku

on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
      
      
      
