name: Deploy Tinyr to Heroku

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
       - uses: actions/checkout@v3
       - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
         with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tinyr"
          heroku_email: "luego1986@gmail.com"
      
      
